### ISSUE TITLE
Imports are broken

### ISSUE THREAD

**Issue by dangerwheeler** [elderamevans/familysearch-python-sdk-opensource#24]
Just got latest. Looks like imports aren't working anymore.

*Simple example:*
from familysearch import FamilySearch
fs = FamilySearch('bar', 'foo', base="https://sandbox.familysearch.org")
fs.login(input("Username: "), getpass())

*Running this gives:*
AttributeError: 'FamilySearch' object has no attribute 'login'

**Comment by rmchurch** [comment]
+1
I tried changing around ordering of the "from . import" statements in __init__.py, and some other ways to make sure the FamilySearch class correctly imports the methods from the Authentication class, but no luck. I'm not exactly sure why the package is organized like this.

**Comment by elderamevans** [comment]
I think I may know what may have caused that....

It may have been the moving of the
```from familysearch import FamilySearch
FamilySearch.__bases__ += (ModuleName,)```
into the class's `__init__` function.

It was originally at the bottom.
I moved it due to other import errors.

As for the orginization, I modeled it (or at least tried to model it) after the [FamilySearch API documentation](https://familysearch.org/developers/docs/api/resources).

**Comment by elderamevans** [comment]
...I know exactly what I did wrong...

Let me fix it.

**Comment by rmchurch** [comment]
Hmmm, the newest commit (a4b99ece56f616f28c299a531de0bafbfaf12c03) is still giving me issues. All of the other class methods are present in an instantiated FamilySearch object, except for those from authentication_.py.

**Comment by elderamevans** [comment]
Sorry about that! I honestly thought I got it.
